implement docker volumes on redis
Jamestth/GoWhereAh pull request #9
Opened 2022-09-01 13:05 UTC by seanleeleelee

- included documentations on redis data persistence testing
- included additional documentations on redis-cli and how to use

2022-09-01 13:27 UTC, Jamestth requested changes
Can you write the Test Redis Persistence in a Readme instead of the rainfall scraper file?

2022-09-01 15:59 UTC, GLeyi approved these changes

2022-09-01 16:31 UTC, naozitios approved these changes

2022-09-02 03:31 UTC, Jamestth approved these changes

2022-09-02 03:35 UTC, merged